sudo: false
language: node_js
node_js:
  - "stable"
before_script:
  - "npm install -g markdown-link-check"
script:
  - "markdown-link-check ./README.md"
  - "markdown-link-check ./CONTRIBUTING.md"
  - "markdown-link-check ./.github/PULL_REQUEST_TEMPLATE.md"
notifications:
  webhooks:
    on_success: never
    urls:
      - "https://www.travisbuddy.com/?insertMode=update"
travisBuddy:
  insertMode: update
