sudo: false
language: node_js
node_js:
  - "stable"
cache: npm
before_script:
  - "npm install -g markdown-link-check"
script:
  - "markdown-link-check ./README.md"
  - "markdown-link-check ./CONTRIBUTING.md"
  - "markdown-link-check ./.github/PULL_REQUEST_TEMPLATE.md"
notifications:
  webhooks:
    urls:
      - "https://www.travisbuddy.com"
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
