sudo: false
language: node_js
node_js:
  - "stable"
cache: npm
before_script:
  - "npm install -g markdown-link-check"
script:
  - "markdown-link-check ./README.md"
  - "markdown-link-check ./CONTRIBUTING.md"
  - "markdown-link-check ./.github/PULL_REQUEST_TEMPLATE.md"
